targets:
  $default:
    builders:
      widget_builder:
        enabled: true

builders:
  widget_builder:
    import: "package:generators/builder.dart"
    builder_factories: ["defaultValuesChecker"]
    build_extensions: {".dart": [".g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
